# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8','11','17', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{matrix.java}}
        cache: maven
    - name: Maven -v
      run: mvn -v
    - name: Build with Maven
      run: mvn -B package --file pom.xml
