name: build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8','11','17', '21']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: maven
      - name: Maven -v
        run: mvn -v
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.timestamp.outputs.time }}
    permissions:
      contents: write
      packages: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Get current time
        id: timestamp
        run: echo "time=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Prepare and perform release
        run: mvn -B release:prepare release:perform -Drevision=${{ ${{ steps.timestamp.outputs.time }}
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}